[package]
name = "rnsh"
authors = ["Corean Fathir <coreanfathir6@gmail.com>"]
version = "0.1.0"
edition = "2021"
rust-version = "1.84"
license = "GPL-3.0-or-later"
repository = "https://github.com/Rena-nf/rnsh"

[dependencies]
parking_lot = "0.12.3"
